alter session set nls_date_format = 'DY MON DD YYYY HH24:MI:SS';
commit;

--
insert all 
    into merch_kind (merch_kind_id, merch_kind) VALUEs(1, 'CD')
    into merch_kind (merch_kind_id, merch_kind) VALUEs(2, 'DVD') 
    into merch_kind (merch_kind_id, merch_kind) VALUEs(3, 'Blue-Ray') 
    into merch_kind (merch_kind_id, merch_kind) VALUEs(4, 'Plate')
select 1 from dual;

--
insert all
    into genre (genre_id, genre_name) values (1, 'Avant-garde')
    into genre (genre_id, genre_name) values (2, 'Blues')
    into genre (genre_id, genre_name) values (3, 'Caribbean')
    into genre (genre_id, genre_name) values (4, 'Country')
    into genre (genre_id, genre_name) values (5, 'Easy listening')
    into genre (genre_id, genre_name) values (6, 'Electronic music')
    into genre (genre_id, genre_name) values (7, 'Folk')
    into genre (genre_id, genre_name) values (8, 'Hip hop')
    into genre (genre_id, genre_name) values (9, 'Jazz')
    into genre (genre_id, genre_name) values (10, 'Latin')
    into genre (genre_id, genre_name) values (11, 'Pop')
    into genre (genre_id, genre_name) values (12, 'R and B and soul')
    into genre (genre_id, genre_name) values (13, 'Rock')
    into genre (genre_id, genre_name) values (14, 'Classical music')
select 1 from dual;

--
insert all
    into employee_job (employee_job_id, employee_job_title) values (1,'Representative')
    into employee_job (employee_job_id, employee_job_title) values (2,'Director')
    into employee_job (employee_job_id, employee_job_title) values (3,'Manager')
    into employee_job (employee_job_id, employee_job_title) values (4,'Coordinator')
    into employee_job (employee_job_id, employee_job_title) values (5,'Liaison')
    into employee_job (employee_job_id, employee_job_title) values (6,'Facilitator')
    into employee_job (employee_job_id, employee_job_title) values (7,'Strategist')
    into employee_job (employee_job_id, employee_job_title) values (8,'Strategist')
    into employee_job (employee_job_id, employee_job_title) values (9,'Engineer')
    into employee_job (employee_job_id, employee_job_title) values (10,'Administrator')
select 1 from dual;

--
insert all 
    into employee(employee_id, employee_name, employee_job_id, employee_phone) VALUES
    (1,'Elmo Mosciski',6,'1-209-798-1424 x00533')
    into employee(employee_id, employee_name, employee_job_id, employee_phone) VALUES
    (2,'Tabitha Robel',5,'908.360.0942')
    into employee(employee_id, employee_name, employee_job_id, employee_phone) VALUES
    (3,'Anjali Rice',8,'373-548-7196 x19798')
    into employee(employee_id, employee_name, employee_job_id, employee_phone) VALUES
    (4,'Kellen Kerluke',10,'167.184.3890')
    into employee(employee_id, employee_name, employee_job_id, employee_phone) VALUES
    (5,'Joesph Collins PhD',1,'1-359-111-6127 x965')
    into employee(employee_id, employee_name, employee_job_id, employee_phone) VALUES
    (6,'Suzanne Lowe',1,'919-620-7738 x1367')
    into employee(employee_id, employee_name, employee_job_id, employee_phone) VALUES
    (7,'Nona Schoen',9,'1-980-141-0285')
    into employee(employee_id, employee_name, employee_job_id, employee_phone) VALUES
    (8,'Haylie Corkery',8,'826.746.7972')
    into employee(employee_id, employee_name, employee_job_id, employee_phone) VALUES
    (9,'Lincoln McGlynn',7,'055-653-8356 x261')
    into employee(employee_id, employee_name, employee_job_id, employee_phone) VALUES
    (10,'Annalise Wisozk',4,'904.774.9443 x7025')
select 1 from dual;

--
insert all
    into client (client_id, client_name, client_address, client_phone) values
    (1, 'Abby Ullrich', 'Lake Aminamouth, 86301 Jedidiah Unions', '297.073.9377 x251')
    into client (client_id, client_name, client_address, client_phone) values
    (2, 'Nicholas Hane', 'Jackland, 154 Nat Estate', '115.097.4841 x08641')
    into client (client_id, client_name, client_address, client_phone) values
    (3, 'Henriette Jacobs', 'Port Juanitatown, 46357 Josiane Ferry', '657.711.6243 x8909')
    into client (client_id, client_name, client_address, client_phone) values
    (4, 'Hershel Towne', 'Aliaton, 018 Wehner Ville', '280-298-6702')
    into client (client_id, client_name, client_address, client_phone) values
    (5, 'Frieda Parisian', 'Arichaven, 14920 Denesik Shoal', '735-884-6282 x9605')
    into client (client_id, client_name, client_address, client_phone) values
    (6, 'Ryann Gleichner', 'Lake Karleyberg, 45035 Gerlach Junctions', '1-722-898-7951 x963')
    into client (client_id, client_name, client_address, client_phone) values
    (7, 'Marley Goldner', 'Merlville, 3864 Lesch Pike', '879-347-0017 x8236')
    into client (client_id, client_name, client_address, client_phone) values
    (8, 'Kathleen Schumm', 'Brooksville, 920 McGlynn Trail', '726.164.3456')
    into client (client_id, client_name, client_address, client_phone) values
    (9, 'Bobby Murray', 'Rogerbury, 13877 Smitham Summit', '045.745.0239 x0111')
    into client (client_id, client_name, client_address, client_phone) values
    (10, 'Faustino Ullrich', 'East Lailatown, 9786 Davis Shoal', '952.814.9361')
    into client (client_id, client_name, client_address, client_phone) values
    (11, 'Susanna Hermann', 'Hintzshire, 18231 Brent Lake', '(085) 015-5861')
    into client (client_id, client_name, client_address, client_phone) values
    (12, 'Zena O'' Kon', 'Rathfort, 54375 Ernser Ramp','013.088.9230 x44620')
    into client (client_id, client_name, client_address, client_phone) values
    (13, 'Hailee Smitham', 'Cruickshankstad, 342 Earlene Passage', '221-161-2423')
    into client (client_id, client_name, client_address, client_phone) values
    (14, 'Malika Powlowski V ','Deckowhaven, 5570 Koss Terrace', '045-297-6691 x783')
    into client (client_id, client_name, client_address, client_phone) values
    (15, 'Ralph Ebert', 'Lake Lesleyview, 67009 Geo Keys', '1-849-232-1509 x561')
select 1 from dual;

--
insert all
  into sales (sale_id, client_id, employee_id, sale_date) values
  (1, 5, 7, to_date('Wed Jan 22 2020 09:53:58', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (2, 10, 7, to_date('Wed Jun 17 2020 18:22:26', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (3, 10, 9, to_date('Fri Jan 03 2020 23:39:50', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (4, 8, 3, to_date('Sat Feb 29 2020 03:42:58', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (5, 11, 5, to_date('Mon Jun 08 2020 10:32:36', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (6, 2, 4, to_date('Sat Jan 11 2020 03:24:26', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (7, 4, 5, to_date('Tue Feb 04 2020 06:46:14', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (8, 12, 8, to_date('Thu Sep 10 2020 08:50:39', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (9, 1, 7, to_date('Fri Aug 28 2020 13:45:31', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (10, 15, 6, to_date('Fri Oct 18 2019 01:01:48', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (11, 6, 1, to_date('Sun Oct 06 2019 07:39:04', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (12, 9, 2, to_date('Mon Aug 24 2020 06:45:19', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (13, 1, 1, to_date('Wed Sep 09 2020 02:43:51', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (14, 9, 2, to_date('Mon Dec 02 2019 05:43:48', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (15, 5, 1, to_date('Tue Mar 17 2020 20:37:30', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (16, 5, 9, to_date('Sun May 10 2020 08:46:33', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (17, 5, 10, to_date('Thu Sep 24 2020 12:56:22', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (18, 14, 7, to_date('Fri Dec 13 2019 04:12:25', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (19, 6, 2, to_date('Thu Aug 20 2020 11:49:19', 'DY MON DD YYYY HH24:MI:SS'))
  into sales (sale_id, client_id, employee_id, sale_date) values
  (20, 6, 5, to_date('Thu Apr 30 2020 16:54:00', 'DY MON DD YYYY HH24:MI:SS'))
select 1 from dual;

--
insert all 
    into sale_quantity_merch(sales_id,merch_id,quantity) values (18, 27, 17)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (3, 6, 16)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (14, 25, 9)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (16, 24, 16)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (18, 34, 15)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (1, 15, 6)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (17, 12, 14)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (15, 39, 2)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (17, 9, 15)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (10, 5, 3)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (9, 6, 2)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (18, 31, 12)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (5, 8, 11)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (15, 4, 20)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (1, 21, 8)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (1, 6, 11)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (16, 6, 4)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (19, 13, 4)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (5, 35, 20)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (9, 29, 7)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (9, 38, 12)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (15, 10, 8)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (14, 37, 11)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (8, 6, 14)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (14, 21, 2)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (16, 32, 3)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (18, 19, 7)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (18, 25, 13)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (12, 8, 14)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (12, 27, 6)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (7, 24, 4)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (14, 17, 14)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (6, 35, 7)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (13, 4, 12)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (9, 20, 1)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (3, 29, 6)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (2, 23, 19)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (18, 12, 16)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (20, 7, 11)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (12, 35, 6)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (19, 26, 7)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (12, 6, 2)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (10, 34, 13)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (4, 12, 20)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (7, 28, 6)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (2, 15, 13)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (15, 32, 4)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (1, 34, 9)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (18, 34, 14)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (3, 20, 4)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (14, 27, 8)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (8, 5, 17)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (9, 39, 17)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (4, 22, 11)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (9, 17, 2)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (19, 32, 11)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (20, 2, 9)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (15, 13, 16)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (5, 36, 1)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (11, 18, 19)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (8, 17, 5)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (8, 11, 11)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (10, 30, 4)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (4, 28, 2)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (9, 33, 19)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (15, 15, 6)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (16, 13, 15)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (5, 1, 13)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (7, 39, 14)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (13, 1, 6)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (7, 37, 7)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (17, 22, 1)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (6, 28, 2)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (10, 17, 7)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (16, 24, 2)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (15, 6, 6)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (20, 13, 20)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (7, 36, 11)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (18, 31, 19)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (13, 36, 14)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (14, 33, 5)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (5, 12, 19)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (20, 12, 20)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (15, 38, 6)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (7, 36, 20)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (5, 38, 6)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (1, 5, 18)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (14, 36, 2)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (10, 23, 15)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (19, 12, 14)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (17, 25, 12)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (3, 16, 16)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (8, 24, 9)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (13, 31, 16)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (9, 17, 14)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (18, 34, 16)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (20, 32, 19)
    into sale_quantity_merch(sales_id,merch_id,quantity) values (19, 28, 6)
select 1 from dual;

--
insert all 
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (1, to_date('2013', 'YYYY'), 'Handmade Fresh Computer', 86.96, 2, 20)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (2, to_date('1980', 'YYYY'), 'Rustic Rubber Tuna', 58.40, 3, 1)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (3, to_date('1981', 'YYYY'), 'Ergonomic Concrete Mouse', 49.27, 1, 1)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (4, to_date('1986', 'YYYY'), 'Tasty Soft Salad', 25.32, 3, 4)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (5, to_date('1987', 'YYYY'), 'Generic Fresh Computer', 8.48, 3, 11)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (6, to_date('1999', 'YYYY'), 'Generic Fresh Shoes', 67.77, 2, 8)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (7, to_date('1986', 'YYYY'), 'Tasty Granite Gloves', 70.52, 3, 18)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (8, to_date('1994', 'YYYY'), 'Incredible Soft Bike', 40.38, 1, 9)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (9, to_date('2003', 'YYYY'), 'Tasty Frozen Chair', 39.65, 1, 19)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (10, to_date('2014', 'YYYY'), 'Ergonomic Rubber Fish', 29.48, 3, 20)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (11, to_date('2015', 'YYYY'), 'Rustic Metal Pants', 58.52, 1, 11)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (12, to_date('2000', 'YYYY'), 'Sleek Metal Table', 36.93, 1, 15)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (13, to_date('1986', 'YYYY'), 'Tasty Granite Soap', 55.9, 4, 5)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (14, to_date('2014', 'YYYY'), 'Incredible Granite Ball', 39.83, 1, 17)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (15, to_date('2002', 'YYYY'), 'Generic Rubber Computer', 57.3, 3, 12)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (16, to_date('2016', 'YYYY'), 'Licensed Concrete Soap', 44.57, 1, 19)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (17, to_date('1999', 'YYYY'), 'Tasty Cotton Keyboard', 44.14, 2, 10)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (18, to_date('2003', 'YYYY'), 'Handcrafted Soft Chips', 13.84, 2, 10)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (19, to_date('2007', 'YYYY'), 'Awesome Cotton Mouse', 44.15, 3, 20)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (20, to_date('1990', 'YYYY'), 'Rustic Steel Mouse', 95.42, 3, 10)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (21, to_date('2004', 'YYYY'), 'Rustic Frozen Bacon', 60.44, 1, 11)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (22, to_date('1982', 'YYYY'), 'Awesome Wooden Pants', 72.51, 4, 12)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (23, to_date('2020', 'YYYY'), 'Incredible Plastic Bike', 31.54, 4, 9)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (24, to_date('2016', 'YYYY'), 'Licensed Fresh Bacon', 97.94, 2, 3)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (25, to_date('2006', 'YYYY'), 'Fantastic Wooden Table', 17.81, 4, 2)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (26, to_date('2019', 'YYYY'), 'Intelligent Concrete Keyboard', 1.23, 2, 1)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (27, to_date('2013', 'YYYY'), 'Handmade Rubber Bacon', 66.37, 2, 18)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (28, to_date('1992', 'YYYY'), 'Generic Cotton Bike', 46.18, 3, 11)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (29, to_date('1993', 'YYYY'), 'Refined Fresh Chips', 28.68, 4, 13)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (30, to_date('2002', 'YYYY'), 'Ergonomic Fresh Computer', 13.95, 1, 14)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (31, to_date('2009', 'YYYY'), 'Small Cotton Soap', 24.12, 2, 8)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (32, to_date('1990', 'YYYY'), 'Fantastic Granite Towels', 25.97, 4, 1)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (33, to_date('2010', 'YYYY'), 'Unbranded Cotton Table', 38.61, 4, 13)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (34, to_date('1999', 'YYYY'), 'Generic Metal Soap', 19.11, 3, 3)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (35, to_date('1993', 'YYYY'), 'Ergonomic Soft Mouse', 51.81, 4, 14)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (36, to_date('2002', 'YYYY'), 'Generic Fresh Table', 52.56, 4, 17)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (37, to_date('2005', 'YYYY'), 'Handmade Concrete Chair', 20.62, 2, 17)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (38, to_date('1987', 'YYYY'), 'Intelligent Soft Soap', 42.50, 4, 11)
    into merch (merch_id, merch_year, merch_title, merch_unit_price, merch_kind_id, company_id) VALUES (39, to_date('2001', 'YYYY'), 'Handmade Granite Soap', 89.74, 2, 11)
select 1 from dual;

--
insert all 
    into company (company_id, company_name) values (1, 'Quigley - Wisozk')
    into company (company_id, company_name) values (2, 'Rutherford - Schmidt')
    into company (company_id, company_name) values (3, 'Konopelski, Ruecker and Roberts')
    into company (company_id, company_name) values (4, 'Tremblay - Kuphal')
    into company (company_id, company_name) values (5, 'Kuvalis - Crona')
    into company (company_id, company_name) values (6, 'Beatty Group')
    into company (company_id, company_name) values (7, 'Fay, Dare and Thompson')
    into company (company_id, company_name) values (8, 'Thompson Group')
    into company (company_id, company_name) values (9, 'Kiehn - Pfeffer')
    into company (company_id, company_name) values (10, 'Ernser LLC')
    into company (company_id, company_name) values (11, 'Satterfield, Larkin and Franecki')
    into company (company_id, company_name) values (12, 'Gulgowski, Berge and Spencer')
    into company (company_id, company_name) values (13, 'Feest - Schiller')
    into company (company_id, company_name) values (14, 'Bahringer - Beatty')
    into company (company_id, company_name) values (15, 'Smitham - Hudson')
    into company (company_id, company_name) values (16, 'Sipes Group')
    into company (company_id, company_name) values (17, 'Thiel Group')
    into company (company_id, company_name) values (18, 'Schamberger Inc')
    into company (company_id, company_name) values (19, 'Reichert and Sons')
    into company (company_id, company_name) values (20, 'McDermott, Kreiger and Ernser')
select 1 from dual;

--
insert all
    into PERFORMER (performer_id, performer_name) values (1, 'Mortimer Simonis')
    into PERFORMER (performer_id, performer_name) values (2, 'Samantha Sawayn')
    into PERFORMER (performer_id, performer_name) values (3, 'Ms. Maureen Stracke')
    into PERFORMER (performer_id, performer_name) values (4, 'Mrs. Santino Lebsack')
    into PERFORMER (performer_id, performer_name) values (5, 'Duane Romaguera')
    into PERFORMER (performer_id, performer_name) values (6, 'Ressie Feest')
    into PERFORMER (performer_id, performer_name) values (7, 'Burnice Shields I')
    into PERFORMER (performer_id, performer_name) values (8, 'Etha Heaney III')
    into PERFORMER (performer_id, performer_name) values (9, 'Mrs. Esperanza Collier')
    into PERFORMER (performer_id, performer_name) values (10, 'Jose Sipes')
    into PERFORMER (performer_id, performer_name) values (11, 'Elyssa Carter')
    into PERFORMER (performer_id, performer_name) values (12, 'Ofelia Stehr')
    into PERFORMER (performer_id, performer_name) values (13, 'Daniella Gutmann Sr.')
    into PERFORMER (performer_id, performer_name) values (14, 'Grant Skiles')
    into PERFORMER (performer_id, performer_name) values (15, 'Elody Zulauf')
select 1 from dual;

--
insert all
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (26, 12)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (31, 13)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (1, 7)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (33, 7)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (20, 5)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (3, 8)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (34, 11)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (18, 1)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (10, 10)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (4, 12)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (20, 8)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (15, 13)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (36, 6)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (8, 2)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (7, 11)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (10, 3)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (16, 13)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (11, 12)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (21, 6)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (37, 9)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (13, 10)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (3, 7)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (29, 9)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (17, 11)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (26, 10)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (31, 6)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (12, 3)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (24, 13)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (39, 8)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (25, 10)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (25, 2)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (25, 9)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (18, 8)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (12, 6)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (39, 3)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (6, 6)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (8, 13)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (22, 2)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (22, 12)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (27, 12)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (27, 2)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (22, 6)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (27, 2)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (1, 4)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (30, 7)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (38, 4)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (12, 11)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (33, 4)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (37, 5)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (33, 6)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (29, 10)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (32, 11)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (20, 7)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (36, 10)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (15, 7)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (13, 1)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (20, 4)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (32, 7)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (24, 1)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (15, 10)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (8, 1)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (18, 6)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (25, 1)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (29, 6)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (34, 3)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (21, 2)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (9, 6)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (21, 7)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (21, 6)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (16, 5)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (12, 13)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (9, 9)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (28, 8)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (35, 5)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (4, 13)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (32, 6)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (4, 12)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (25, 14)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (14, 8)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (33, 2)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (17, 1)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (21, 1)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (3, 14)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (35, 5)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (25, 9)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (37, 11)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (26, 14)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (34, 11)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (37, 8)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (18, 2)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (11, 6)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (21, 4)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (8, 2)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (10, 12)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (14, 11)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (5, 10)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (18, 3)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (32, 1)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (29, 11)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (33, 5)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (8, 6)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (14, 12)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (12, 8)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (13, 5)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (23, 13)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (18, 14)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (37, 1)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (36, 1)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (18, 7)
    into MERCH_GENRE (MERCH_ID, GENRE_ID) VALUES (30, 6)
select 1 from dual;

--
insert all
    into merch_performer (merch_id, performer_id) values (11, 8)
    into merch_performer (merch_id, performer_id) values (1, 11)
    into merch_performer (merch_id, performer_id) values (5, 12)
    into merch_performer (merch_id, performer_id) values (25, 13)
    into merch_performer (merch_id, performer_id) values (4, 6)
    into merch_performer (merch_id, performer_id) values (29, 7)
    into merch_performer (merch_id, performer_id) values (6, 8)
    into merch_performer (merch_id, performer_id) values (24, 2)
    into merch_performer (merch_id, performer_id) values (27, 12)
    into merch_performer (merch_id, performer_id) values (27, 6)
    into merch_performer (merch_id, performer_id) values (39, 9)
    into merch_performer (merch_id, performer_id) values (37, 5)
    into merch_performer (merch_id, performer_id) values (21, 4)
    into merch_performer (merch_id, performer_id) values (36, 6)
    into merch_performer (merch_id, performer_id) values (27, 10)
    into merch_performer (merch_id, performer_id) values (28, 6)
    into merch_performer (merch_id, performer_id) values (24, 2)
    into merch_performer (merch_id, performer_id) values (30, 14)
    into merch_performer (merch_id, performer_id) values (13, 5)
    into merch_performer (merch_id, performer_id) values (31, 15)
    into merch_performer (merch_id, performer_id) values (37, 14)
    into merch_performer (merch_id, performer_id) values (13, 9)
    into merch_performer (merch_id, performer_id) values (32, 3)
    into merch_performer (merch_id, performer_id) values (11, 11)
    into merch_performer (merch_id, performer_id) values (18, 15)
    into merch_performer (merch_id, performer_id) values (6, 8)
    into merch_performer (merch_id, performer_id) values (6, 10)
    into merch_performer (merch_id, performer_id) values (22, 15)
    into merch_performer (merch_id, performer_id) values (23, 1)
    into merch_performer (merch_id, performer_id) values (3, 1)
    into merch_performer (merch_id, performer_id) values (15, 15)
    into merch_performer (merch_id, performer_id) values (32, 10)
    into merch_performer (merch_id, performer_id) values (12, 1)
    into merch_performer (merch_id, performer_id) values (11, 3)
    into merch_performer (merch_id, performer_id) values (30, 9)
    into merch_performer (merch_id, performer_id) values (28, 12)
    into merch_performer (merch_id, performer_id) values (13, 15)
    into merch_performer (merch_id, performer_id) values (6, 3)
    into merch_performer (merch_id, performer_id) values (1, 9)
    into merch_performer (merch_id, performer_id) values (32, 1)
    into merch_performer (merch_id, performer_id) values (33, 6)
    into merch_performer (merch_id, performer_id) values (29, 3)
    into merch_performer (merch_id, performer_id) values (4, 5)
    into merch_performer (merch_id, performer_id) values (13, 14)
    into merch_performer (merch_id, performer_id) values (20, 12)
    into merch_performer (merch_id, performer_id) values (16, 3)
    into merch_performer (merch_id, performer_id) values (9, 13)
    into merch_performer (merch_id, performer_id) values (34, 9)
    into merch_performer (merch_id, performer_id) values (10, 13)
    into merch_performer (merch_id, performer_id) values (2, 12)
    into merch_performer (merch_id, performer_id) values (18, 6)
    into merch_performer (merch_id, performer_id) values (18, 6)
    into merch_performer (merch_id, performer_id) values (7, 2)
    into merch_performer (merch_id, performer_id) values (27, 6)
    into merch_performer (merch_id, performer_id) values (30, 11)
    into merch_performer (merch_id, performer_id) values (5, 11)
    into merch_performer (merch_id, performer_id) values (36, 6)
    into merch_performer (merch_id, performer_id) values (33, 4)
    into merch_performer (merch_id, performer_id) values (21, 13)
select 1 from dual;